name: Auto Build Lichee RV Debian Linux Bootable Image.
on:
  push:
    tags:
      - '*'
jobs:
  build-all-os:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install depends
          run: sudo apt install -y qemu-user-static qemu-system qemu-utils qemu-system-misc binfmt-support

        - name: Build
          run: |
            docker-compose build
            echo ${{runner.workspace}}
            mkdir -p port

        - name: Create Image
          run: |
            echo ${{runner.workspace}}
            docker-compose up
            ls -l ${{runner.workspace}}
        - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
              draft: false
              prerelease: false
              release_name: Release  ${{ github.ref }}
              tag_name: ${{ github.ref }}
              body_path: CHANGES.md
          env:
              GITHUB_TOKEN: ${{ github.token }}
        - name: Upload asset to release
          uses: csexton/release-asset-action@v2
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            pattern: "/port/lichee*.img.xz"
            github-token: ${{ secrets.GITHUB_TOKEN }}
