name: Auto Build Lichee RV Debian Linux Bootable Image.
on:
  push:
    tags:
      - '*'
jobs:
  build-all-os:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install depends
          run: sudo apt install -y qemu-user-static qemu-system qemu-utils qemu-system-misc binfmt-support

        - name: Prepare
          run: |
            echo ${{runner.workspace}}
            mkdir -p port
            #echo "Hello World" > port/lichee_rv_86_foo.img.xz
            #echo "Hello World" > port/lichee_rv_dock_foo.img.xz
        - name: Build
          run: |
            docker-compose build

        - name: Create Lichee RV Dock Image
          run: |
            docker-compose up lichee_rv
            ls -l port/*
        - name: Create Lichee RV 86 panel Image
          run: |
            docker-compose up rv86panel
            ls -l port/*
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              port/lichee_rv_86*.img.xz
              port/lichee_rv_dock*.img.xz
