name: Auto Build Lichee RV Debian Linux Bootable Image.
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
 
jobs:
  build-all-os:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install depends
          run: sudo apt-get update && sudo apt-get install -y qemu-user-static qemu-system qemu-utils qemu-system-misc binfmt-support

        - name: Prepare
          run: |
            echo ${{runner.workspace}}
            mkdir -p lichee_rv_86
            mkdir -p lichee_rv_dock
        - name: Build
          run: |
            docker-compose build

        - name: Create Lichee RV Dock Image
          run: |
            docker-compose up dock
            ls -l lichee_rv_dock/*
        - name: Create Lichee RV 86 panel Image
          run: |
            docker-compose up panel
            ls -l lichee_rv_86/*
        - uses: actions/upload-artifact@v3
          with:
            name: dock-artifact
            path: lichee_rv_dock/lichee_rv_dock*
        
        - uses: actions/upload-artifact@v3
          with:
            name: all-artifact
            path: lichee_rv_dock/*
